POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "test01",
    "password": "test"
}

###
# @prompt token

GET http://localhost:8000/api/member/
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token
POST http://localhost:8000/api/member/
Content-Type: application/json

{
  "username": "test02",
  "email": "test02@co.jp",
  "password": "is0397sv"
}

###
# @prompt token

PATCH http://localhost:8000/api/member/15/
Content-Type: application/json
Authorization: Token {{token}}

{
  "username": "eee"
}

###
# @prompt token

GET http://localhost:8000/api/comic/master/?member_id=1
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

GET http://localhost:8000/api/comic/master/?member_id=1&exclude_id=658340a9-a66f-41e2-a03a-4e7fb861d2fe
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

GET http://localhost:8000/api/comic/version/?member_id=1
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

GET http://localhost:8000/api/comic/version/?member_id=1&title_id=c98f151b-7023-4bd7-b8a0-f54147cdb704
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

GET http://localhost:8000/api/review/master/?member_id=1
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token
POST http://localhost:8000/api/review/master/
Content-Type: application/json
Authorization: Token {{token}}

{
  "member": "1",
  "comicID": "658340a9-a66f-41e2-a03a-4e7fb861d2fe",
  "scoreAlpha": 1.2,
  "scoreBeta": 2.1,
  "scoreCamma": 3.2,
  "scoreDelta": 4.2,
  "scoreEpsilon": 3.3,
  "comment": "hello"
}

###
# @prompt token
PATCH http://localhost:8000/api/review/master/be617063-2a5f-46a7-b483-02f68000f5f2/
Content-Type: application/json
Authorization: Token {{token}}

{
  "comment": "hello, world"
}