POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "fffffffffff",
    "password": "eeeeee"
}

###
# @prompt token

GET http://localhost:8000/api/member/
Content-Type: application/json
Authorization: Token {{token}}

###

POST http://localhost:8000/api/member/
Content-Type: application/json

{
  "username": "test02",
  "email": "test02@co.jp",
  "password": "is0397sv"
}

###
# @prompt token

PATCH http://localhost:8000/api/member/15/
Content-Type: application/json
Authorization: Token {{token}}

{
  "username": "eee"
}

###
# @prompt token

GET http://localhost:8000/api/review/master/?member_id=1
Content-Type: application/json
Authorization: Token {{token}}

