POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###
# @prompt token

GET http://localhost:8000/api/member/
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token
POST http://localhost:8000/api/member/
Content-Type: application/json

{
  "username": "test02",
  "email": "test02@co.jp",
  "password": "is0397sv"
}

###
# @prompt token

PATCH http://localhost:8000/api/member/15/
Content-Type: application/json
Authorization: Token {{token}}

{
  "username": "eee"
}

###
# @prompt token

GET http://localhost:8000/api/review/master/?member_id=1
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token
POST http://localhost:8000/api/review/master/
Content-Type: application/json
Authorization: Token {{token}}

{
  "member": "1",
  "comicMaster": "f4d8b1df-1d95-45c9-9c2a-ed855a6aa8e3",
  "scoreAlpha": 1.2,
  "scoreBeta": 2.1,
  "scoreCamma": 3.2,
  "scoreDelta": 4.2,
  "scoreEpsilon": 3.3,
  "comment": "hello"
}

###
# @prompt token
PATCH http://localhost:8000/api/review/master/1d39f9df-bd7f-423b-a134-756df0d8a78e/
Content-Type: application/json
Authorization: Token {{token}}

{
  "comment": "hello, world"
}