/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComicTable: typeof import('./src/components/comictable/ComicTable.vue')['default']
    HelloWorld: typeof import('./src/components/home/HelloWorld.vue')['default']
    Popup: typeof import('./src/components/commons/Popup.vue')['default']
    ProfileDialog: typeof import('./src/components/topbar/ProfileDialog.vue')['default']
    ReviewDialog: typeof import('./src/components/comictable/ReviewDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/topbar/TopBar.vue')['default']
  }
}
