# Generated by Django 4.0.2 on 2024-02-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'メンバー'},
        ),
    ]
